/*
 * TraceMate - Generic Fine-Grained Visual Matching
 *
 * This module compares visualDetails generated by the
 * FastAPI visual_details.py extractor.
 *
 * It is object-agnostic:
 *   - bags
 *   - bottles
 *   - wallets
 *   - phones
 *   - books
 *   - clothes
 *   - keys
 *   - etc.
 *
 * It does NOT replace MobileNetV2 or CLIP.
 *
 * It provides additional evidence:
 *   - colour structure
 *   - shape
 *   - foreground geometry
 *   - 3x3 local regions
 *   - local texture / edge changes
 *   - visible OCR text
 *
 * Similarity percentages here are engineering similarity
 * measurements, NOT model accuracy.
 */


/* =========================================================
   BASIC HELPERS
========================================================= */

function clamp(
  value,
  minimum = 0,
  maximum = 1
) {
  const number = Number(value);

  if (!Number.isFinite(number)) {
    return minimum;
  }

  return Math.max(
    minimum,
    Math.min(
      maximum,
      number
    )
  );
}


function numberOrNull(value) {
  const number = Number(value);

  return Number.isFinite(number)
    ? number
    : null;
}


function round(
  value,
  digits = 1
) {
  const factor =
    10 ** digits;

  return Math.round(
    Number(value) * factor
  ) / factor;
}


function normalizeText(value) {
  return String(
    value ?? ''
  )
    .toLowerCase()
    .replace(
      /[^a-z0-9]+/g,
      ' '
    )
    .trim();
}


function tokenize(value) {
  return [
    ...new Set(
      normalizeText(value)
        .split(/\s+/)
        .filter(
          token =>
            token.length >= 2
        )
    )
  ];
}


/* =========================================================
   NUMBER / VECTOR COMPARISON
========================================================= */

function numericSimilarity(
  a,
  b,
  maxDifference
) {
  const first =
    numberOrNull(a);

  const second =
    numberOrNull(b);

  if (
    first === null ||
    second === null ||
    maxDifference <= 0
  ) {
    return null;
  }

  return clamp(
    1 -
      Math.abs(
        first - second
      ) /
      maxDifference
  );
}


function vectorSimilarity(
  a,
  b,
  maxDifference = 255
) {
  if (
    !Array.isArray(a) ||
    !Array.isArray(b) ||
    a.length !== b.length ||
    a.length === 0
  ) {
    return null;
  }

  let total = 0;
  let count = 0;

  for (
    let i = 0;
    i < a.length;
    i += 1
  ) {
    const similarity =
      numericSimilarity(
        a[i],
        b[i],
        maxDifference
      );

    if (similarity !== null) {
      total += similarity;
      count += 1;
    }
  }

  return count > 0
    ? total / count
    : null;
}


/* =========================================================
   COLOUR COMPARISON
========================================================= */

function colorSimilarity(
  lost,
  found
) {
  if (
    !lost ||
    !found
  ) {
    return {
      available: false,
      score: 0,
      percentage: null,
      reason: 'Colour details unavailable'
    };
  }

  const lostColor =
    lost.color || {};

  const foundColor =
    found.color || {};

  const components = [];

  const meanRgbSimilarity =
    vectorSimilarity(
      lostColor.mean_rgb,
      foundColor.mean_rgb,
      255
    );

  if (
    meanRgbSimilarity !== null
  ) {
    components.push(
      {
        weight: 0.45,
        value: meanRgbSimilarity
      }
    );
  }

  const saturationSimilarity =
    numericSimilarity(
      lostColor.saturation,
      foundColor.saturation,
      1
    );

  if (
    saturationSimilarity !== null
  ) {
    components.push(
      {
        weight: 0.25,
        value: saturationSimilarity
      }
    );
  }

  const brightnessSimilarity =
    numericSimilarity(
      lostColor.brightness,
      foundColor.brightness,
      1
    );

  if (
    brightnessSimilarity !== null
  ) {
    components.push(
      {
        weight: 0.20,
        value: brightnessSimilarity
      }
    );
  }

  const hueSimilarity =
    numericSimilarity(
      lostColor.hue,
      foundColor.hue,
      0.5
    );

  if (
    hueSimilarity !== null
  ) {
    components.push(
      {
        weight: 0.10,
        value: hueSimilarity
      }
    );
  }

  if (!components.length) {
    return {
      available: false,
      score: 0,
      percentage: null,
      reason: 'No comparable colour descriptors'
    };
  }

  const totalWeight =
    components.reduce(
      (sum, item) =>
        sum + item.weight,
      0
    );

  const score =
    components.reduce(
      (sum, item) =>
        sum +
        (
          item.value *
          item.weight
        ),
      0
    ) /
    totalWeight;

  const lostDominant =
    lostColor.dominant || {};

  const foundDominant =
    foundColor.dominant || {};

  const lostName =
    normalizeText(
      lostDominant.name
    );

  const foundName =
    normalizeText(
      foundDominant.name
    );

  let dominantColorMatch =
    null;

  if (
    lostName &&
    foundName
  ) {
    dominantColorMatch =
      lostName === foundName
        ? 1
        : 0;
  }

  return {
    available: true,

    score:

      dominantColorMatch === null
        ? score
        :
          (
            score * 0.75
            +
            dominantColorMatch * 0.25
          ),

    percentage:
      round(
        (
          dominantColorMatch === null
            ? score
            :
              (
                score * 0.75
                +
                dominantColorMatch * 0.25
              )
        ) * 100,
        1
      ),

    dominantColorMatch:
      dominantColorMatch === null
        ? null
        : Boolean(
            dominantColorMatch
          ),

    lostDominantColor:
      lostDominant.name || null,

    foundDominantColor:
      foundDominant.name || null
  };
}


/* =========================================================
   SHAPE COMPARISON
========================================================= */

function shapeSimilarity(
  lost,
  found
) {
  if (
    !lost ||
    !found
  ) {
    return {
      available: false,
      score: 0,
      percentage: null
    };
  }

  const lostShape =
    lost.shape || {};

  const foundShape =
    found.shape || {};

  const components = [];

  const aspectSimilarity =
    numericSimilarity(
      lostShape.aspect_ratio,
      foundShape.aspect_ratio,
      Math.max(
        1,
        Math.abs(
          Number(
            lostShape.aspect_ratio
          ) || 1
        )
      )
    );

  if (
    aspectSimilarity !== null
  ) {
    components.push(
      {
        weight: 0.45,
        value: aspectSimilarity
      }
    );
  }

  const fillSimilarity =
    numericSimilarity(
      lostShape.fill_ratio,
      foundShape.fill_ratio,
      1
    );

  if (
    fillSimilarity !== null
  ) {
    components.push(
      {
        weight: 0.30,
        value: fillSimilarity
      }
    );
  }

  const edgeSimilarity =
    numericSimilarity(
      lostShape.edge_density,
      foundShape.edge_density,
      1
    );

  if (
    edgeSimilarity !== null
  ) {
    components.push(
      {
        weight: 0.25,
        value: edgeSimilarity
      }
    );
  }

  if (!components.length) {
    return {
      available: false,
      score: 0,
      percentage: null
    };
  }

  const weight =
    components.reduce(
      (sum, component) =>
        sum + component.weight,
      0
    );

  const score =
    components.reduce(
      (sum, component) =>
        sum +
        (
          component.value *
          component.weight
        ),
      0
    ) /
    weight;

  return {
    available: true,

    score,

    percentage:
      round(
        score * 100,
        1
      ),

    aspectRatio:
      numberOrNull(
        lostShape.aspect_ratio
      ) !== null &&
      numberOrNull(
        foundShape.aspect_ratio
      ) !== null
        ? {
            lost:
              lostShape.aspect_ratio,
            found:
              foundShape.aspect_ratio
          }
        : null,

    fillRatio:
      numberOrNull(
        lostShape.fill_ratio
      ) !== null &&
      numberOrNull(
        foundShape.fill_ratio
      ) !== null
        ? {
            lost:
              lostShape.fill_ratio,
            found:
              foundShape.fill_ratio
          }
        : null
  };
}


/* =========================================================
   BOUNDING BOX COMPARISON
========================================================= */

function boundingBoxSimilarity(
  lost,
  found
) {
  const lostBox =
    lost?.shape?.foreground_bbox;

  const foundBox =
    found?.shape?.foreground_bbox;

  if (
    !lostBox ||
    !foundBox
  ) {
    return null;
  }

  const values = [
    numericSimilarity(
      lostBox.left,
      foundBox.left,
      0.5
    ),

    numericSimilarity(
      lostBox.top,
      foundBox.top,
      0.5
    ),

    numericSimilarity(
      lostBox.right,
      foundBox.right,
      0.5
    ),

    numericSimilarity(
      lostBox.bottom,
      foundBox.bottom,
      0.5
    )
  ].filter(
    value =>
      value !== null
  );

  if (!values.length) {
    return null;
  }

  return (
    values.reduce(
      (sum, value) =>
        sum + value,
      0
    )
    /
    values.length
  );
}


/* =========================================================
   LOCAL REGION COMPARISON
========================================================= */

function compareRegion(
  lostRegion,
  foundRegion
) {
  if (
    !lostRegion ||
    !foundRegion
  ) {
    return null;
  }

  const components = [];

  const rgbSimilarity =
    vectorSimilarity(
      lostRegion.mean_rgb,
      foundRegion.mean_rgb,
      255
    );

  if (
    rgbSimilarity !== null
  ) {
    components.push(
      {
        weight: 0.40,
        value: rgbSimilarity
      }
    );
  }

  const brightnessSimilarity =
    numericSimilarity(
      lostRegion.brightness,
      foundRegion.brightness,
      1
    );

  if (
    brightnessSimilarity !== null
  ) {
    components.push(
      {
        weight: 0.15,
        value: brightnessSimilarity
      }
    );
  }

  const saturationSimilarity =
    numericSimilarity(
      lostRegion.saturation,
      foundRegion.saturation,
      1
    );

  if (
    saturationSimilarity !== null
  ) {
    components.push(
      {
        weight: 0.10,
        value: saturationSimilarity
      }
    );
  }

  const edgeSimilarity =
    numericSimilarity(
      lostRegion.edge_density,
      foundRegion.edge_density,
      1
    );

  if (
    edgeSimilarity !== null
  ) {
    components.push(
      {
        weight: 0.15,
        value: edgeSimilarity
      }
    );
  }

  const textureSimilarity =
    numericSimilarity(
      lostRegion.texture,
      foundRegion.texture,
      1
    );

  if (
    textureSimilarity !== null
  ) {
    components.push(
      {
        weight: 0.20,
        value: textureSimilarity
      }
    );
  }

  if (!components.length) {
    return null;
  }

  let score =
    components.reduce(
      (sum, component) =>
        sum +
        (
          component.value *
          component.weight
        ),
      0
    );

  const lostColor =
    normalizeText(
      lostRegion.dominant_color
    );

  const foundColor =
    normalizeText(
      foundRegion.dominant_color
    );

  if (
    lostColor &&
    foundColor
  ) {
    score =
      (
        score * 0.80
        +
        (
          lostColor === foundColor
            ? 1
            : 0
        ) * 0.20
      );
  }

  return clamp(
    score
  );
}


/* =========================================================
   LOCAL REGION NAME HELPERS
========================================================= */

const REGION_NAMES = [
  'upper-left',
  'upper-center',
  'upper-right',

  'middle-left',
  'center',
  'middle-right',

  'lower-left',
  'lower-center',
  'lower-right'
];


function regionCoordinates(
  name
) {
  const index =
    REGION_NAMES.indexOf(
      name
    );

  if (index < 0) {
    return null;
  }

  return {
    row:
      Math.floor(
        index / 3
      ),

    column:
      index % 3
  };
}


/*
 * Compare a region with its corresponding region first.
 * If the scores are low, also check nearby regions.
 *
 * This makes the comparison somewhat more tolerant of
 * small camera framing shifts.
 */

function bestRegionMatch(
  regionName,
  lostRegions,
  foundRegions
) {
  const lostRegion =
    lostRegions?.[regionName];

  if (!lostRegion) {
    return null;
  }

  const coordinates =
    regionCoordinates(
      regionName
    );

  if (!coordinates) {
    return null;
  }

  const candidates = [];

  for (
    const candidateName
    of REGION_NAMES
  ) {

    const candidate =
      foundRegions?.[
        candidateName
      ];

    if (!candidate) {
      continue;
    }

    const candidateCoordinates =
      regionCoordinates(
        candidateName
      );

    if (!candidateCoordinates) {
      continue;
    }

    const distance =
      Math.abs(
        coordinates.row -
        candidateCoordinates.row
      )
      +
      Math.abs(
        coordinates.column -
        candidateCoordinates.column
      );

    /*
     * Don't allow a region to match a very distant
     * region. At most one grid step away.
     */

    if (distance > 1) {
      continue;
    }

    const score =
      compareRegion(
        lostRegion,
        candidate
      );

    if (score === null) {
      continue;
    }

    candidates.push(
      {
        region:
          candidateName,

        score,

        distance
      }
    );
  }

  candidates.sort(
    (a, b) => {

      if (
        b.score !==
        a.score
      ) {
        return (
          b.score -
          a.score
        );
      }

      return (
        a.distance -
        b.distance
      );
    }
  );

  return (
    candidates[0]
    ||
    null
  );
}


/* =========================================================
   LOCAL REGION SUMMARY
========================================================= */

function localRegionSimilarity(
  lost,
  found
) {
  const lostRegions =
    lost?.regions || {};

  const foundRegions =
    found?.regions || {};

  const results = [];

  for (
    const regionName
    of REGION_NAMES
  ) {

    const match =
      bestRegionMatch(
        regionName,
        lostRegions,
        foundRegions
      );

    if (!match) {
      results.push(
        {
          region:
            regionName,

          score: null,

          percentage: null,

          matchedRegion: null
        }
      );

      continue;
    }

    results.push(
      {
        region:
          regionName,

        score:
          match.score,

        percentage:
          round(
            match.score * 100,
            1
          ),

        matchedRegion:
          match.region
      }
    );
  }

  const usable =
    results.filter(
      result =>
        result.score !== null
    );

  if (!usable.length) {
    return {
      available: false,

      score: 0,

      percentage: null,

      regions: [],

      mismatches: []
    };
  }

  const total =
    usable.reduce(
      (sum, result) =>
        sum + result.score,
      0
    );

  const overall =
    total /
    usable.length;

  /*
   * Regions below this threshold are reported as
   * possible local visual differences.
   */

  const mismatches =
    usable
      .filter(
        result =>
          result.score < 0.55
      )
      .map(
        result => ({
          region:
            result.region,

          matchedRegion:
            result.matchedRegion,

          similarity:
            result.percentage,

          reason:
            'Local colour, texture or edge structure differs'
        })
      );

  return {
    available: true,

    score: overall,

    percentage:
      round(
        overall * 100,
        1
      ),

    regions: results,

    mismatches
  };
}


/* =========================================================
   OCR / VISIBLE TEXT COMPARISON
========================================================= */

function ocrSimilarity(
  lost,
  found
) {
  const lostOcr =
    lost?.ocr || {};

  const foundOcr =
    found?.ocr || {};

  const lostTokens =
    tokenize(
      lostOcr.text ||
      (
        Array.isArray(
          lostOcr.tokens
        )
          ? lostOcr.tokens.join(
              ' '
            )
          : ''
      )
    );

  const foundTokens =
    tokenize(
      foundOcr.text ||
      (
        Array.isArray(
          foundOcr.tokens
        )
          ? foundOcr.tokens.join(
              ' '
            )
          : ''
      )
    );

  if (
    !lostTokens.length ||
    !foundTokens.length
  ) {
    return {
      available: false,

      score: 0,

      percentage: null,

      sharedTokens: []
    };
  }

  const foundSet =
    new Set(
      foundTokens
    );

  const sharedTokens =
    lostTokens.filter(
      token =>
        foundSet.has(
          token
        )
    );

  const union = new Set(
    [
      ...lostTokens,
      ...foundTokens
    ]
  );

  const score =
    union.size > 0
      ? sharedTokens.length /
        union.size
      : 0;

  return {
    available: true,

    score,

    percentage:
      round(
        score * 100,
        1
      ),

    sharedTokens
  };
}


/* =========================================================
   MAIN COMPARISON
========================================================= */

function compareVisualDetails(
  lost,
  found
) {
  const lostAvailable =
    Boolean(
      lost?.available
    );

  const foundAvailable =
    Boolean(
      found?.available
    );

  if (
    !lostAvailable ||
    !foundAvailable
  ) {
    return {
      available: false,

      percentage: null,

      colorSimilarityPercentage:
        null,

      shapeSimilarityPercentage:
        null,

      foregroundSimilarityPercentage:
        null,

      regionSimilarityPercentage:
        null,

      ocrSimilarityPercentage:
        null,

      mismatches: [],

      notes: [
        'Fine-grained visual details are unavailable for one or both images.'
      ]
    };
  }

  const color =
    colorSimilarity(
      lost,
      found
    );

  const shape =
    shapeSimilarity(
      lost,
      found
    );

  const foreground =
    boundingBoxSimilarity(
      lost,
      found
    );

  const regions =
    localRegionSimilarity(
      lost,
      found
    );

  const ocr =
    ocrSimilarity(
      lost,
      found
    );

  const components = [];

  if (
    color.score !== null &&
    color.available
  ) {
    components.push(
      {
        name: 'colour',
        weight: 0.25,
        score:
          color.score
      }
    );
  }

  if (
    shape.score !== null &&
    shape.available
  ) {
    components.push(
      {
        name: 'shape',
        weight: 0.20,
        score:
          shape.score
      }
    );
  }

  if (
    foreground !== null
  ) {
    components.push(
      {
        name: 'foreground',
        weight: 0.10,
        score:
          foreground
      }
    );
  }

  if (
    regions.score !== null &&
    regions.available
  ) {
    components.push(
      {
        name: 'regions',
        weight: 0.35,
        score:
          regions.score
      }
    );
  }

  if (
    ocr.score !== null &&
    ocr.available
  ) {
    components.push(
      {
        name: 'ocr',
        weight: 0.10,
        score:
          ocr.score
      }
    );
  }

  if (!components.length) {
    return {
      available: false,

      percentage: null,

      colorSimilarityPercentage:
        color.percentage,

      shapeSimilarityPercentage:
        shape.percentage,

      foregroundSimilarityPercentage:
        foreground === null
          ? null
          : round(
              foreground * 100,
              1
            ),

      regionSimilarityPercentage:
        regions.percentage,

      ocrSimilarityPercentage:
        ocr.percentage,

      mismatches:
        regions.mismatches || [],

      notes: [
        'No usable fine-grained visual components were available.'
      ]
    };
  }

  const totalWeight =
    components.reduce(
      (sum, component) =>
        sum +
        component.weight,
      0
    );

  const overall =
    components.reduce(
      (sum, component) =>
        sum +
        (
          component.score *
          component.weight
        ),
      0
    ) /
    totalWeight;

  const mismatches = [
    ...(regions.mismatches || [])
  ];

  /*
   * Strong global mismatches.
   */

  if (
    shape.percentage !== null &&
    shape.percentage < 45
  ) {
    mismatches.push(
      {
        region:
          'overall',

        similarity:
          shape.percentage,

        reason:
          'Overall shape structure is substantially different'
      }
    );
  }

  if (
    color.percentage !== null &&
    color.percentage < 45
  ) {
    mismatches.push(
      {
        region:
          'overall',

        similarity:
          color.percentage,

        reason:
          'Overall colour structure is substantially different'
      }
    );
  }

  const notes = [];

  if (
    color.percentage !== null
  ) {
    notes.push(
      `Colour structure similarity: ${color.percentage}%`
    );
  }

  if (
    shape.percentage !== null
  ) {
    notes.push(
      `Shape similarity: ${shape.percentage}%`
    );
  }

  if (
    regions.percentage !== null
  ) {
    notes.push(
      `Local-region similarity: ${regions.percentage}%`
    );
  }

  if (
    ocr.percentage !== null
  ) {
    notes.push(
      `Visible-text similarity: ${ocr.percentage}%`
    );
  }

  if (
    mismatches.length
  ) {
    notes.push(
      `${mismatches.length} local/global visual difference(s) detected.`
    );
  }

  return {
    available: true,

    percentage:
      round(
        overall * 100,
        1
      ),

    score:
      overall,

    colorSimilarityPercentage:
      color.percentage,

    shapeSimilarityPercentage:
      shape.percentage,

    foregroundSimilarityPercentage:
      foreground === null
        ? null
        : round(
            foreground * 100,
            1
          ),

    regionSimilarityPercentage:
      regions.percentage,

    ocrSimilarityPercentage:
      ocr.percentage,

    dominantColorMatch:
      color.dominantColorMatch,

    lostDominantColor:
      color.lostDominantColor,

    foundDominantColor:
      color.foundDominantColor,

    sharedOcrTokens:
      ocr.sharedTokens || [],

    regionDetails:
      regions.regions,

    mismatches,

    components,

    notes
  };
}


module.exports = {
  compareVisualDetails,
  colorSimilarity,
  shapeSimilarity,
  localRegionSimilarity,
  ocrSimilarity
};
